/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package news.app;

import news.list.LinkedList;

import static news.utilities.StringUtils.join;
import static news.utilities.StringUtils.split;
import static news.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
